steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - '--build-arg'
      - 'SESSION_SECRET=${_SESSION_SECRET}'
      - '--build-arg'
      - 'NEXT_PUBLIC_USER_SERVICE_URL=${_NEXT_PUBLIC_USER_SERVICE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_MATCHING_SERVICE_URL=${_NEXT_PUBLIC_MATCHING_SERVICE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_QUESTION_SERVICE_URL=${_NEXT_PUBLIC_QUESTION_SERVICE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_COLLAB_SERVICE_URL=${_NEXT_PUBLIC_COLLAB_SERVICE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_COLLAB_SERVICE_WS_URL=${_NEXT_PUBLIC_COLLAB_SERVICE_WS_URL}'
      - ui-service
      - '-f'
      - ui-service/Dockerfile
    id: Build
    secretEnv: ['SESSION_SECRET', 'NEXT_PUBLIC_USER_SERVICE_URL', 'NEXT_PUBLIC_MATCHING_SERVICE_URL', 'NEXT_PUBLIC_QUESTION_SERVICE_URL', 'NEXT_PUBLIC_COLLAB_SERVICE_URL', 'NEXT_PUBLIC_COLLAB_SERVICE_WS_URL']
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud

images:
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _DEPLOY_REGION: asia-southeast1
  _AR_HOSTNAME: asia-southeast1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _AR_PROJECT_ID: cs3219-peerprep-g30
  _PLATFORM: managed
  _SERVICE_NAME: cs3219-ay2526s1-project-g30
  _TRIGGER_ID: 75ef2963-cd0e-4a56-892c-3ad1d15067be
  _SESSION_SECRET: 'session-secret'
  _NEXT_PUBLIC_USER_SERVICE_URL: 'next-public-user-service-url'
  _NEXT_PUBLIC_MATCHING_SERVICE_URL: 'next-public-matching-service-url'
  _NEXT_PUBLIC_QUESTION_SERVICE_URL: 'next-public-question-service-url'
  _NEXT_PUBLIC_COLLAB_SERVICE_URL: 'next-public-collab-service-url'
  _NEXT_PUBLIC_COLLAB_SERVICE_WS_URL: 'next-public-collab-service-ws-url'

secrets:
  - versionName: projects/cs3219-peerprep-g30/secrets/session-secret/versions/latest
    env: '_SESSION_SECRET'
  - versionName: projects/cs3219-peerprep-g30/secrets/next-public-user-service-url/versions/latest
    env: '_NEXT_PUBLIC_USER_SERVICE_URL'
  - versionName: projects/cs3219-peerprep-g30/secrets/next-public-matching-service-url/versions/latest
    env: '_NEXT_PUBLIC_MATCHING_SERVICE_URL'
  - versionName: projects/cs3219-peerprep-g30/secrets/next-public-question-service-url/versions/latest
    env: '_NEXT_PUBLIC_QUESTION_SERVICE_URL'
  - versionName: projects/cs3219-peerprep-g30/secrets/next-public-collab-service-url/versions/latest
    env: '_NEXT_PUBLIC_COLLAB_SERVICE_URL'
  - versionName: projects/cs3219-peerprep-g30/secrets/next-public-collab-service-ws-url/versions/latest
    env: '_NEXT_PUBLIC_COLLAB_SERVICE_WS_URL'

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - cs3219-ay2526s1-project-g30
