# Dev - matching-service
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: golang:1.24-alpine
    id: Test
    entrypoint: sh
    args:
      - -c
      - |
        cd matching-service && \
        go mod download && \
        go test ./... -v

  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - --no-cache
      - -t
      - asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-dev/matching-service:$SHORT_SHA
      - -t
      - asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-dev/matching-service:latest
      - -f
      - matching-service/Dockerfile
      - matching-service
    waitFor: ['Test']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Resolve-URLs
    entrypoint: bash
    args:
      - -c
      - |
        COLLAB_URL=$(gcloud run services describe collab-service-dev --region=asia-southeast1 --format='value(status.url)')
        QN_URL=$(gcloud run services describe question-service-dev --region=asia-southeast1 --format='value(status.url)')
        echo "COLLAB_SERVICE_URL=$$COLLAB_URL" >> urls.env
        echo "QUESTION_SERVICE_URL=$$QN_URL" >> urls.env
    waitFor: ['Build']

  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - --all-tags
      - asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-dev/matching-service
    waitFor: ['Build']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Deploy
    entrypoint: bash
    args:
      - -c
      - |
        source urls.env
        gcloud run deploy matching-service-dev \
           --image=asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-dev/matching-service:$SHORT_SHA \
           --region=asia-southeast1 \
           --platform=managed \
           --allow-unauthenticated \
           --port=8080 \
           --set-env-vars=COLLAB_SERVICE_URL=$$COLLAB_SERVICE_URL,QUESTION_SERVICE_URL=$$QUESTION_SERVICE_URL \
           --memory=512Mi \
           --cpu=1 \
           --min-instances=0 \
           --max-instances=3 \
           --timeout=60
    waitFor: ['Push','Resolve-URLs']

images:
  - asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-dev/matching-service:$SHORT_SHA

tags:
  - dev
  - matching-service

timeout: 1200s
