# Dev - user-service

steps:
  - name: node:lts-alpine
    id: Test
    entrypoint: sh
    args:
      - -c
      - |
        cd user-service && \
        npm ci && \
        npm test 2>/dev/null || echo "No tests configured"

  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - --no-cache
      - -t
      - asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-dev/user-service:$SHORT_SHA
      - -t
      - asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-dev/user-service:latest
      - -f
      - user-service/Dockerfile
      - user-service
    waitFor: ['Test']

  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - --all-tags
      - asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-dev/user-service
    waitFor: ['Build']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - user-service-dev
      - --image=asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-dev/user-service:$SHORT_SHA
      - --region=asia-southeast1
      - --platform=managed
      - --allow-unauthenticated
      - --port=5001
      - --set-secrets=MONGO_URI=MONGO_URI_USER_SERVICE:latest,JWT_SECRET=JWT_SECRET:latest,SENDGRID_API_KEY=SENDGRID_API_KEY:latest,GCS_BUCKET_NAME=GCS_BUCKET_NAME:latest
      - --memory=512Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=3
      - --timeout=60
    waitFor: ['Push']

images:
  - asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-dev/user-service:$SHORT_SHA

tags:
  - dev
  - user-service

timeout: 1200s
