# Production - question-service
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Resolve-URLs
    entrypoint: bash
    args:
      - -c
      - |
         USER_URL=$(gcloud run services describe user-service-production --region=asia-southeast1 --format='value(status.url)')
         echo "USER_SERVICE_URL=$$USER_URL/api/users" >> urls.env

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Deploy
    entrypoint: bash
    args:
      - -c
      - |
        source urls.env
        gcloud run deploy question-service-production \
          --image=asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-staging/question-service:latest \
          --region=asia-southeast1 \
          --platform=managed \
          --allow-unauthenticated \
          --port=4000 \
          --set-secrets=MONGO_URI=MONGO_URI_QUESTION_SERVICE:latest \
          --set-env-vars=USER_SERVICE_URL=$$USER_SERVICE_URL \
          --memory=512Mi \
          --cpu=1 \
          --min-instances=1 \
          --max-instances=100 \
          --timeout=60
    waitFor: ['Resolve-URLs']

tags:
  - production
  - question-service

timeout: 900s

