# Production - question-service
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Pull the latest staging image
  - name: gcr.io/cloud-builders/docker
    id: Pull-Staging
    args:
      - pull
      - asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-staging/question-service:latest

  # Re-tag to production repository
  - name: gcr.io/cloud-builders/docker
    id: Tag-Production
    args:
      - tag
      - asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-staging/question-service:latest
      - asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-production/question-service:latest
    waitFor: ['Pull-Staging']

  # Push to production repository
  - name: gcr.io/cloud-builders/docker
    id: Push-Production
    args:
      - push
      - asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-production/question-service:latest
    waitFor: ['Tag-Production']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Resolve-URLs
    entrypoint: bash
    args:
      - -c
      - |
         USER_URL=$(gcloud run services describe user-service-production --region=asia-southeast1 --format='value(status.url)')
         echo "USER_SERVICE_URL=$$USER_URL/api/users" >> urls.env
    waitFor: ['Push-Production']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Deploy
    entrypoint: bash
    args:
      - -c
      - |
        source urls.env
        gcloud run deploy question-service-production \
          --image=asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-production/question-service:latest \
          --region=asia-southeast1 \
          --platform=managed \
          --allow-unauthenticated \
          --port=4000 \
          --set-secrets=MONGO_URI=MONGO_URI_QUESTION_SERVICE:latest \
          --set-env-vars=USER_SERVICE_URL=$$USER_SERVICE_URL \
          --memory=512Mi \
          --cpu=1 \
          --min-instances=1 \
          --max-instances=100 \
          --timeout=60
    waitFor: ['Resolve-URLs']

images:
  - asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-production/question-service:latest

tags:
  - production
  - question-service

timeout: 900s

