# Production - ui-service

steps:
  - name: gcr.io/cloud-builders/gcloud
    id: Retag
    entrypoint: bash
    args:
      - -c
      - |
        gcloud artifacts docker tags add \
          asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-staging/ui-service:$SHORT_SHA \
          asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-production/ui-service:$SHORT_SHA && \
        gcloud artifacts docker tags add \
          asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-staging/ui-service:$SHORT_SHA \
          asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-production/ui-service:latest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Resolve-URLs
    entrypoint: bash
    args:
      - -c
      - |
        USER_URL=$(gcloud run services describe user-service-production --region=asia-southeast1 --format='value(status.url)')
        QN_URL=$(gcloud run services describe question-service-production --region=asia-southeast1 --format='value(status.url)')
        MATCH_URL=$(gcloud run services describe matching-service-production --region=asia-southeast1 --format='value(status.url)')
        COLLAB_URL=$(gcloud run services describe collab-service-production --region=asia-southeast1 --format='value(status.url)')
        echo "NEXT_PUBLIC_USER_SERVICE_URL=${USER_URL}/api/users" >> urls.env
        echo "NEXT_PUBLIC_QUESTION_SERVICE_URL=${QN_URL}" >> urls.env
        echo "NEXT_PUBLIC_MATCHING_SERVICE_URL=${MATCH_URL}/api/v1" >> urls.env
        echo "NEXT_PUBLIC_COLLAB_SERVICE_URL=${COLLAB_URL}/" >> urls.env
        echo "NEXT_PUBLIC_COLLAB_SERVICE_WS_URL=wss://${COLLAB_URL#https://}/" >> urls.env
    waitFor: ['Retag']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Deploy
    entrypoint: bash
    args:
      - -c
      - |
        source urls.env
        gcloud run deploy ui-service-production \
          --image=asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-production/ui-service:$SHORT_SHA \
          --region=asia-southeast1 \
          --platform=managed \
          --allow-unauthenticated \
          --port=3000 \
          --memory=512Mi \
          --cpu=1 \
          --min-instances=1 \
          --max-instances=10 \
          --timeout=60
    waitFor: ['Resolve-URLs']

tags:
  - production
  - ui-service

timeout: 900s
