# Production - ui-service
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Pull the latest staging image
  - name: gcr.io/cloud-builders/docker
    id: Pull-Staging
    args:
      - pull
      - asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-staging/ui-service:latest

  # Re-tag to production repository
  - name: gcr.io/cloud-builders/docker
    id: Tag-Production
    args:
      - tag
      - asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-staging/ui-service:latest
      - asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-production/ui-service:latest
    waitFor: ['Pull-Staging']

  # Push to production repository
  - name: gcr.io/cloud-builders/docker
    id: Push-Production
    args:
      - push
      - asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-production/ui-service:latest
    waitFor: ['Tag-Production']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Resolve-URLs
    entrypoint: bash
    args:
      - -c
      - |
        USER_URL=$(gcloud run services describe user-service-production --region=asia-southeast1 --format='value(status.url)')
        QN_URL=$(gcloud run services describe question-service-production --region=asia-southeast1 --format='value(status.url)')
        MATCH_URL=$(gcloud run services describe matching-service-production --region=asia-southeast1 --format='value(status.url)')
        COLLAB_URL=$(gcloud run services describe collab-service-production --region=asia-southeast1 --format='value(status.url)')
         echo "NEXT_PUBLIC_USER_SERVICE_URL=$$USER_URL/api/users" >> urls.env
         echo "NEXT_PUBLIC_QUESTION_SERVICE_URL=$$QN_URL" >> urls.env
         echo "NEXT_PUBLIC_MATCHING_SERVICE_URL=$$MATCH_URL/api/v1" >> urls.env
         echo "NEXT_PUBLIC_COLLAB_SERVICE_URL=$$COLLAB_URL/" >> urls.env
         echo "NEXT_PUBLIC_COLLAB_SERVICE_WS_URL=wss://$${COLLAB_URL#https://}/" >> urls.env
    waitFor: ['Push-Production']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Deploy
    entrypoint: bash
    args:
      - -c
      - |
        source urls.env
         gcloud run deploy ui-service-production \
           --image=asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-production/ui-service:latest \
           --region=asia-southeast1 \
           --platform=managed \
           --allow-unauthenticated \
           --port=3000 \
           --set-secrets=SESSION_SECRET=SESSION_SECRET:latest \
           --set-env-vars=NEXT_PUBLIC_USER_SERVICE_URL=$$NEXT_PUBLIC_USER_SERVICE_URL,NEXT_PUBLIC_QUESTION_SERVICE_URL=$$NEXT_PUBLIC_QUESTION_SERVICE_URL,NEXT_PUBLIC_MATCHING_SERVICE_URL=$$NEXT_PUBLIC_MATCHING_SERVICE_URL,NEXT_PUBLIC_COLLAB_SERVICE_URL=$$NEXT_PUBLIC_COLLAB_SERVICE_URL,NEXT_PUBLIC_COLLAB_SERVICE_WS_URL=$$NEXT_PUBLIC_COLLAB_SERVICE_WS_URL \
           --memory=1Gi \
           --cpu=1 \
           --min-instances=1 \
           --max-instances=100 \
           --timeout=720 \
           --session-affinity
    waitFor: ['Resolve-URLs']

images:
  - asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-production/ui-service:latest

tags:
  - production
  - ui-service

timeout: 900s

