# Production - user-service
# Deploys the latest staging image to production

steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - user-service-production
      - --image=asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-staging/user-service:latest
      - --region=asia-southeast1
      - --platform=managed
      - --allow-unauthenticated
      - --port=5001
      - --set-secrets=MONGO_URI=MONGO_URI_USER_SERVICE:latest,JWT_SECRET=JWT_SECRET:latest,SENDGRID_API_KEY=SENDGRID_API_KEY:latest,GCS_BUCKET_NAME=GCS_BUCKET_NAME:latest
      - --memory=512Mi
      - --cpu=1
      - --min-instances=1
      - --max-instances=100
      - --timeout=60

tags:
  - production
  - user-service

timeout: 900s
