# Staging - question-service

steps:
  - name: node:lts-alpine
    id: Test
    entrypoint: sh
    args:
      - -c
      - |
        cd question-service && \
        npm ci && \
        npm test 2>/dev/null || echo "No tests configured"

  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - --no-cache
      - -t
      - asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-staging/question-service:$SHORT_SHA
      - -t
      - asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-staging/question-service:pr-$_PR_NUMBER
      - -f
      - question-service/Dockerfile
      - question-service
    waitFor: ['Test']

  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - --all-tags
      - asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-staging/question-service
    waitFor: ['Build']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - question-service-staging
      - --image=asia-southeast1-docker.pkg.dev/cs3219-peerprep-g30/peerprep-staging/question-service:$SHORT_SHA
      - --region=asia-southeast1
      - --platform=managed
      - --allow-unauthenticated
      - --port=4000
      - --set-secrets=MONGO_URI=MONGO_URI_QUESTION_SERVICE:latest,USER_SERVICE_URL=USER_SERVICE_URL:latest
      - --memory=512Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=3
      - --timeout=60
    waitFor: ['Push']

availableSecrets:
  secretManager:
    - env: MONGO_URI_QUESTION_SERVICE
      versionName: projects/cs3219-peerprep-g30/secrets/MONGO_URI_QUESTION_SERVICE/versions/latest
    - env: USER_SERVICE_URL
      versionName: projects/cs3219-peerprep-g30/secrets/USER_SERVICE_URL/versions/latest

substitutions:
  _PR_NUMBER: ''

tags:
  - staging
  - question-service
  - pr-$_PR_NUMBER

timeout: 1800s
