options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/question-service'
      - '.'
    dir: 'question-service'

  # Step 2: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/question-service'

  # Step 3: Deploy to Cloud Run with secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'peerprep-qnsvc',
        '--image',
        'gcr.io/$PROJECT_ID/question-service',
        '--region',
        'asia-southeast1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--set-secrets',
        'MONGO_URI=question_db_uri:latest,USER_SERVICE_URL=user_service_url:latest'
      ]

images:
  - 'gcr.io/$PROJECT_ID/question-service'
